# Generated by Django 4.1.2 on 2022-10-06 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.RemoveField(
            model_name='allergen',
            name='allergen_name',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='allergen',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
        migrations.AddField(
            model_name='allergen',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=120, verbose_name='Название аллергена'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='menu',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='in_menus', to='food_plan.allergen', verbose_name='Исключить аллергены'),
        ),
        migrations.AddField(
            model_name='menu',
            name='calories_per_day',
            field=models.IntegerField(default=0, verbose_name='Калорий в день (всего)'),
        ),
        migrations.AddField(
            model_name='menu',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menu',
            name='period',
            field=models.CharField(choices=[('3', '3 мес.'), ('12', '12 мес.')], default='3', max_length=10, verbose_name='Срок подписки'),
        ),
        migrations.AddField(
            model_name='menu',
            name='persons',
            field=models.IntegerField(default=1, verbose_name='Количество персон'),
        ),
        migrations.AddField(
            model_name='menu',
            name='with_breakfasts',
            field=models.BooleanField(default=True, verbose_name='Завтраки'),
        ),
        migrations.AddField(
            model_name='menu',
            name='with_desserts',
            field=models.BooleanField(default=True, verbose_name='Десерты'),
        ),
        migrations.AddField(
            model_name='menu',
            name='with_lunches',
            field=models.BooleanField(default=True, verbose_name='Обеды'),
        ),
        migrations.AddField(
            model_name='menu',
            name='with_suppers',
            field=models.BooleanField(default=True, verbose_name='Ужины'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('breakfast', 'завтрак'), ('lunch', 'обед'), ('supper', 'ужин'), ('dessert', 'десерт')], default='завтрак', max_length=10, verbose_name='Тип блюда'),
        ),
        migrations.AddField(
            model_name='unit',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Сокращение'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='in_recipes', to='food_plan.ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True, verbose_name='Инструкция приготовления'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Единица измерения продукта'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=120, verbose_name='Название')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='Цена за штуку')),
                ('allergen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='food_plan.allergen', verbose_name='Название аллергена')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='of_products', to='food_plan.unit', verbose_name='Единицы измерения')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='food_plan.product', verbose_name='Продукт'),
        ),
    ]
