# Generated by Django 4.1.2 on 2022-10-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_plan', '0002_alter_menu_options_remove_allergen_allergen_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='portions',
            field=models.IntegerField(default=1, verbose_name='Порция'),
        ),
    ]
