# Generated by Django 4.1.2 on 2022-10-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_plan', '0004_alter_recipe_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.IntegerField(default=1, verbose_name='Количество кКал'),
            preserve_default=False,
        ),
    ]
