# Generated by Django 4.1.2 on 2022-10-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_plan', '0004_remove_ingredient_product_ingredient_allergen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(default='1 ложка', max_length=120, verbose_name='Измерение ингредиента'),
        ),
    ]
