# Generated by Django 4.1.2 on 2022-10-08 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_plan', '0005_recipe_calories'),
        ('food_plan', '0007_remove_recipe_ingredients_ingredient_recipe'),
    ]

    operations = [
    ]
