# Generated by Django 4.1.2 on 2022-10-09 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_plan', '0008_merge_20221008_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='allergen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='on_ingredients', to='food_plan.allergen', verbose_name='Название аллергена'),
        ),
    ]
